#!/bin/bash

function reload {
    git pull
    docker-compose -f /docker/docker-compose.yml -p multidocker up $1 --build -d
    if [ "$1" == "website" ]; then
        docker-compose -f /docker/docker-compose.yml -p multidocker up asset-server --build -d
    fi
}

for dir in /app/*/     # list directories in the form "/app/dirname/"
do
    dir=${dir%*/}      # remove the trailing "/"
    echo ${dir}
    cd ${dir}
    git fetch
    git status|grep "is behind" && reload ${dir##*/}
done
echo gittower waiting ...
