#!/bin/bash
BASE_URL=https://github.com/stt-datacore
./watch website $BASE_URL/website $WEBSITE_BRANCH
./watch site-server $BASE_URL/site-server $SERVER_BRANCH
./watch asset-server $BASE_URL/asset-server $ASSET_BRANCH