version: '3'
services:
    datacoredb:
        image: mongo:4.4.6
        container_name: datacoredb
        volumes:
            - ./mongo-volume:/data/db
        ports:
            - '27017-27019:27017-27019'
        environment:
            - MONGO_INITDB_DATABASE=user
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=secret