global:
  scrape_interval: 5s
scrape_configs:
- job_name: cadvisor
  static_configs:
  - targets:
    - cadvisor:8080
- job_name: 'node-exporter'
  static_configs:
  - targets:
    - node_exporter:9100
