version: '3'
volumes:
    sitebuild:
    assets:
    profiles:
    traindata:
    nginx-logs:
    site-logs:
    bot-logs:
    datacore-mongo:

services:
    gittower:
        image: datacore/gittower
        build: 
            context: contexts/gittower
            args:
                ALPINE_VERSION: ${ALPINE_VERSION}
                NODE_VERSION: ${NODE_VERSION}
        deploy:
            restart_policy: 
                condition: on-failure
        container_name: gittower  
        env_file:
            - .env
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - .:/docker
        profiles: ["all", "gittower"]

    pm2-discord:
        image: datacore/pm2-discord
        build: 
            context: contexts/pm2-discord
            args:
                ALPINE_VERSION: ${ALPINE_VERSION}
                NODE_VERSION: ${NODE_VERSION}
                PM2_ERROR_URL: ${PM2_ERROR_URL}
                PM2_INFO_URL: ${PM2_INFO_URL}
        env_file:
            - .env
        profiles: ["all", "fullstack", "site-server", "website", "bot"]
        
    website:
        build:
            context: contexts/website
            additional_contexts:
                source: https://github.com/stt-datacore/website.git#${WEBSITE_BRANCH}
            args:
                ALPINE_VERSION: ${ALPINE_VERSION}
                NODE_VERSION: ${NODE_VERSION}                       
        env_file:
            - .env
            - ./conf/website.env
        deploy:
            restart_policy: 
                condition: on-failure
                
        container_name: DCWebsite  
        volumes:
            - sitebuild:/sitebuild:rw
        profiles: [ "all", "website", "asset-server", "site-server", "fullstack" ]

    asset-server:
        image: datacore/asset-server
        build:
            context: contexts/asset-server 
            additional_contexts:
                source: https://github.com/stt-datacore/asset-server.git#${ASSET_BRANCH}
            args:
                ALPINE_VERSION: ${ALPINE_VERSION} 
                NODE_VERSION: ${NODE_VERSION}

        container_name: DCAssetServer 
        deploy:
            restart_policy: 
                condition: on-failure
        volumes:
            - ${ASSETS_DIR}:/assets:rw
        environment:
            - OUT_PATH=/assets/
        profiles: [ "all", "asset-server", "website", "fullstack" ]

    datacoredb:
        image: mongo:4.4.6
        container_name: datacoredb
        volumes:
            - datacore-mongo:/data/db
        env_file:
            - .env
        profiles: ["all", "site-server", "bot", "fullstack"]

    local-dev-db:
        image: mongo:4.4.6
        container_name: local-dev-db
        volumes:
            - datacore-mongo:/data/db
        ports:
            - '27017-27019:27017-27019'
        env_file:
            - .env
        profiles: ["local-mongo"]

    site-server:
        image: datacore/site-server
        build:
            context: contexts/site-server
            additional_contexts: 
                source: https://github.com/stt-datacore/site-server.git#${SERVER_BRANCH}
                pm2-discord: contexts/pm2-discord
            target: ${BUILD_TYPE}
            args:
                $NODE_VERSION:
        container_name: DCSiteServer 
        deploy:
            restart_policy: 
                condition: on-failure
        ports:
            - "4420:4420"
        volumes:
            - ${LOG_PATH}:/data/logs:rw
            - ${PROFILE_DATA_PATH}:/profiles:rw
            - ${SQLITE_DB}:/datacore.db
        env_file:
            - .env
            - ./conf/site-server.env
        depends_on:
            - pm2-discord
            - datacoredb
        profiles: ["all", "site-server", "fullstack", "bot"]

    nginx:
        image: nginx:alpine${ALPINE_VERSION}
        container_name: NginxServer
        deploy:
            restart_policy:
                condition: on-failure
        ports:
            - "80:80"
            - "442:442"
        volumes:
            - sitebuild:/sitebuild:ro
            - ${ASSETS_DIR}:/assets:ro
            - ${PROFILE_DATA_PATH}:/profiles:ro
            - nginx-logs:/var/log/nginx:rw
            - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf:rw
        depends_on:
            - site-server
            - datacoredb
        profiles: [ "all", "website", "asset-server", "site-server", "fullstack", "bot" ]

    node_exporter:
        image: prom/node-exporter
        container_name: node_exporter
        ports:
            - "9100:9100"
        profiles: [ "all", "monitoring" ]

    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        ports:
            - "9090:9090"
        command: 
            - --config.file=/etc/prometheus/prometheus.yml
        volumes:
            - ./contexts/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
        depends_on:
            - cadvisor
        profiles: [ "all", "monitoring" ]

    cadvisor:
        image: gcr.io/cadvisor/cadvisor:latest
        container_name: cadvisor
        deploy:
            restart_policy: 
                condition: on-failure
        ports:
            - "8080:8080"
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
        command: [ "--housekeeping_interval=30s", "--docker_only", "--disable_metrics=disk,network,tcp,udp,percpu,sched,process" ] 
        profiles: [ "all", "monitoring" ]

    rsync-host:
        image: hermsi/alpine-sshd
        container_name: RSyncHost
        deploy:
            restart_policy: 
                condition: on-failure
        ports:
            - "1337:22"
        volumes:
            - sitebuild:/sitebuild:rw
            - ${ASSETS_DIR}:/data/assets:ro
            - ${PROFILE_DATA_PATH}:/profiles:rw
            - traindata:/data/traindata:rw
            - nginx-logs:/logs/nginx:ro
            - site-logs:/logs/site-server:ro
        env_file:
            - ./conf/rsync.env
        profiles: [ "all", "rsync", "fullstack" ]

    cpp-image-analysis:
        image: datacore/cpp-image-analysis
        build: 
            context: contexts/cpp-image-analysis
            additional_contexts:
                source: https://github.com/stt-datacore/cpp-image-analysis.git#${CPP_BRANCH}
            args:
                ALPINE_VERSION:
        container_name: DCImageAnalysis 
        deploy:
            restart_policy: 
                condition: on-failure
        env_file:
            - .env
            - ./conf/bot.env
            - ./conf/cpp-image-analysis.env
        ports:
            - 5000:5000
        volumes:
            - sitebuild:/sitebuild:ro
            - traindata:/traindata:rw
        depends_on:
            - pm2-discord
            - nginx
            - website
        profiles: [ "all", "bot" ]

    bot: 
        image: datacore/bot
        build:
            context: contexts/bot
            additional_contexts: 
                source: https://github.com/stt-datacore/bot.git#${BOT_BRANCH}
            target: ${BUILD_TYPE}
            args:
                NODE_VERSION:
        container_name: DCBot
        deploy:
            restart_policy: 
                condition: on-failure
        volumes:
            - sitebuild:/sitebuild:ro
            - ${ASSETS_DIR}:/data/assets:ro
            - bot-logs:/data/logs:rw
            - ${PROFILE_DATA_PATH}:/profiles:rw
            - ${SQLITE_DB}:/datacore.db
        env_file:
            - .env
            - ./conf/bot.env
        depends_on:
            - cpp-image-analysis
            - datacoredb
        profiles: ["all", "bot"]